### Load in NumPy (remember to pip install numpy first)

In [ ]:
import numpy as np

### The Basics

In [ ]:
#We are defining an array and giving input as integer with 32 bits
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [ ]:
#we are defining an array and giving input as float although we have not defined the data type as in the first case
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [ ]:
# Get Dimension
a.ndim

1

In [ ]:
# Get Shape
b.shape

(2, 3)

In [ ]:
# Get Type - we can know what type of data we have in array
a.dtype

dtype('int32')

In [ ]:
# Get Size
a.itemsize

4

In [ ]:
# Get total size (here 3*4)
a.nbytes

12

In [ ]:
# Get number of elements
a.size

3

### Accessing/Changing specific elements, rows, columns, etc

In [ ]:
import numpy as np

In [ ]:
#creating new array
ab = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(ab)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
# Get a specific element [r, c]
ab[1, 5]

13

In [ ]:
# Get a specific row 
p=ab[0, :]
print(p)

[1 2 3 4 5 6 7]


In [ ]:
# Get a specific column
ab[:, 2]

array([ 3, 10])

In [ ]:
# Getting a little more fancy [startindex:endindex:stepsize]
ab[0, 1:-1:2]

array([2, 4, 6])

In [ ]:
#changing the elements in the array
ab[1,5] = 20

ab[:,2] = [1,2]
print(ab)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


*3-d example

In [ ]:
bc = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(bc)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# Get specific element (work outside in) , [matrix no.,row,coloumn]
bc[0,1,1]

4

In [ ]:
bc

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

### Initializing Different Types of Arrays

In [ ]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# All 1s matrix [number of matrices,row,coloumns]
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [ ]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [ ]:
# Any other number (full_like)
np.full_like(a, 4)

array([4, 4, 4])

In [ ]:
# Random decimal numbers [number of matrices,row,coloumns]
np.random.rand(3,4,3)

array([[[0.65210625, 0.70560954, 0.86811335],
        [0.64663992, 0.54792267, 0.78416088],
        [0.69934293, 0.69470295, 0.72423397],
        [0.03130528, 0.38914239, 0.5274503 ]],

       [[0.29326665, 0.76309698, 0.52015311],
        [0.99223783, 0.50092833, 0.59410032],
        [0.84418778, 0.72922579, 0.61233398],
        [0.24551115, 0.41149175, 0.86818636]],

       [[0.39532473, 0.63225822, 0.34368615],
        [0.54542723, 0.87759133, 0.8481033 ],
        [0.77455711, 0.59044817, 0.40491797],
        [0.8108602 , 0.22240882, 0.10353637]]])

In [ ]:
# Random Integer values [-4,8 is the range of values]
np.random.randint(-4,8, size=(3,3))

array([[ 3,  7, -3],
       [ 5,  5, -1],
       [-1,  5,  7]])

In [ ]:
# The identity matrix [in brackets we mentioned 5 because we want 5 by 5 identity matrix]
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)
#we are trying to merge z with output , {range of rows,range of coloumns}
output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##### Be careful when copying arrays!!!

In [ ]:
#copying arrays
abc = np.array([1,2,3])
bz = abc.copy()
bz[0] = 100

print(bz)

[100   2   3]


### Mathematics

In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
#adding 2 to all elements
a + 2

array([3, 4, 5, 6])

In [ ]:
#subtracting 2 from all elements
a - 2

array([-1,  0,  1,  2])

In [ ]:
#multiplying all elements  by 2
a * 2

array([2, 4, 6, 8])

In [ ]:
#dividing all elements  by 2
a / 2

array([0.5, 1. , 1.5, 2. ])

In [ ]:
#adding two arrays a and b
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [ ]:
#raising the power of all elements to 2
a ** 2

array([ 1,  4,  9, 16])

In [ ]:
# Take the sin
np.cos(a)



array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [ ]:
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

##### Linear Algebra

In [ ]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [ ]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [ ]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

##### Statistics

In [ ]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.min(stats)

1

In [ ]:
np.max(stats, axis=1)

array([3, 6])

In [ ]:
np.sum(stats, axis=0)

array([5, 7, 9])

### Reorganizing Arrays

In [ ]:
#we are unable to reorganize because before has size 8
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((2,3))
print(after)

[[1 2 3 4]
 [5 6 7 8]]


ValueError: ignored

In [ ]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Miscellaneous
##### Load Data from File

In [ ]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


##### Boolean Masking and Advanced Indexing

In [ ]:
(~((filedata > 50) & (filedata < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])