In [ ]:
import numpy as np

In [ ]:
myPythonList = [2,4,8,3]
print(myPythonList)

[2, 4, 8, 3]


In [ ]:
numpy_array_from_list = np.array(myPythonList)
numpy_array_from_list

array([2, 4, 8, 3])

In [ ]:
#convert python list to a numpy array by using the object np.array
a  = np.array([2,4,8,3])
print(a)

[2 4 8 3]


In [ ]:
x=numpy_array_from_list + 10
print(x)

[12 14 18 13]


In [ ]:
#shape of array
a  = np.array([1,2,3])
print(a.shape)
print(a.dtype)

(3,)
int64


In [ ]:
#float type
b  = np.array([1.1,2.0,3.2])
print(b.dtype)

float64


In [ ]:
c = np.array([(1,2,3),
              (4,5,6)])
print(c)

[[1 2 3]
 [4 5 6]]


In [ ]:
d = np.array([
    [[1, 2,3],
        [4, 5, 6]],
    [[7, 8,9],
        [10, 11, 12]]
])
print(d.shape)
(2, 2, 3)
print(d)

(2, 2, 3)
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
#np.zeros Python function is used to create a matrix full of zeroes
import numpy as np
x=np.zeros((3,3), dtype=np.int16)
print(x)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
import numpy as np
y=np.ones((2,2,3), dtype=np.int16)
print(y.shape)	
print(y)

(2, 2, 3)
[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


In [ ]:
#reshape the data from wide to long
import numpy as np
e  = np.array([(1,2,7), (4,8,6)])
print(e)
e.reshape(3,2)

[[1 2 7]
 [4 8 6]]


array([[1, 2],
       [7, 4],
       [8, 6]])

In [ ]:
#you can flatten the array in the following way
e.flatten()

array([1, 2, 7, 4, 8, 6])

In [ ]:
#With hstack you can appened data horizontally
import numpy as np
f = np.array([1,2,3])
g = np.array([4,5,6])

print('Horizontal Append:', np.hstack((f, g)))

Horizontal Append: [1 2 3 4 5 6]


In [ ]:
#With vstack you can appened data vertically
import numpy as np
f = np.array([1,2,3])
g = np.array([4,5,6])

print('Vertical Append:', np.vstack((f, g)))

Vertical Append: [[1 2 3]
 [4 5 6]]


In [ ]:
#generating random number
normal_array = np.random.normal(5, 0.5, 10)
print(normal_array)	

[5.87377067 4.96404969 5.34963474 4.85035488 5.77626281 4.73778095
 5.27847272 4.24621643 4.91343137 4.48947213]


In [ ]:
#to convert input into array
A = np.matrix(np.ones((6,4)))		
print(A)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
np.asarray(A)[2]=2
print(A)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
#inbuilt numpy function that returns an ndarray object containing evenly spaced values within a defined interval
np.arange(1, 16)	

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
np.arange(1, 24, 4)

array([ 1,  5,  9, 13, 17, 21])

In [ ]:
#Linspace gives evenly spaced samples
import numpy as np
np.linspace(1.0, 10.0, num=20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [ ]:
np.linspace(1.0, 5.0, num=5, endpoint=False)

array([1. , 1.8, 2.6, 3.4, 4.2])

In [ ]:
#to return even spaced numbers on a log scale
np.logspace(3.0, 4.0, num=4)

array([ 1000.        ,  2154.43469003,  4641.58883361, 10000.        ])

In [ ]:
x = np.array([1,2,3], dtype=np.complex128)
x.itemsize

16

In [ ]:
#Indexing and slicing Slicing data
import numpy as np
e  = np.array([(14,5,89), (7,12,9)])
print(e)

[[14  5 89]
 [ 7 12  9]]


In [ ]:
## First column
print('First row:', e[0])

## Second col
print('Second row:', e[1])

First row: [14  5 89]
Second row: [ 7 12  9]


In [ ]:
print('Second column:', e[:,1])

Second column: [ 5 12]


In [ ]:
## Second Row, two values
print(e[1, :2])

[ 7 12]


In [ ]:
#Second column 2 values
print(e[:2,1])

[ 5 12]


In [ ]:
import numpy as np
normal_array = np.random.normal(5, 0.5, 10)
print(normal_array)	

[5.25548469 5.18522557 6.15494465 4.47154447 4.6207293  4.72467211
 4.78493691 4.27521577 4.90803    5.39460986]


In [ ]:
# Min 
print(np.min(normal_array))

# Max 
print(np.max(normal_array))

# Mean 
print(np.mean(normal_array))

# Median
print(np.median(normal_array))

# Sd
print(np.std(normal_array))

4.275215767597795
6.154944646201288
4.977539332490716
4.846483456601652
0.5160513497366255


In [ ]:
#dot product in numpy
f = np.array([1,2])
g = np.array([4,5])
### 1*4+2*5
np.dot(f, g)

14

In [ ]:
#matrix multiplication in numpy
h = [[1,2],[3,4]] 
i = [[5,6],[7,8]] 
### 1*5+2*7 = 19
np.matmul(h, i)

array([[19, 22],
       [43, 50]])

In [ ]:
#to inverse a matrix in numpy
A = np.array([[62, 1, 1],
              [4, -2, 5],
              [2, 81, 7]])
  
# Calculating the inverse of the matrix
print(np.linalg.inv(A))

[[ 0.01632383 -0.00288297 -0.00027271]
 [ 0.00070126 -0.01683029  0.01192146]
 [-0.01277856  0.19557426  0.00498675]]


In [ ]:
# creating a 2X2 Numpy matrix
n_array = np.array([[50, 29], [30, 44]])
  
# Displaying the Matrix
print("Numpy Matrix is:")
print(n_array)
  
# calculating the determinant of matrix
det = np.linalg.det(n_array)
  
print("\nDeterminant of given 2X2 matrix:")
print(int(det))

Numpy Matrix is:
[[50 29]
 [30 44]]

Determinant of given 2X2 matrix:
1330


In [ ]:
#finding rank of a matrix
mx = np.array([[1,1,1,2],[0,1,2,4],[1,5,3,8]])

np.linalg.matrix_rank(mx)

3

In [ ]:
#Eigenvectors And Eigenvalues
example_matrix = np.array([
  [1,2,3,4],
  [5,6,7,8],
  [9,10,11,12],
  [13,14,15,16]
])
eigenvalues, eigenvectors = np.linalg.eig(example_matrix)
print(eigenvalues, eigenvectors)

[ 3.62093727e+01 -2.20937271e+00 -5.14138333e-16 -2.08943529e-15] [[-0.15115432 -0.72704996  0.01790738 -0.26832672]
 [-0.34923733 -0.28320876  0.38415354  0.71367217]
 [-0.54732033  0.16063243 -0.82202921 -0.62236419]
 [-0.74540333  0.60447363  0.41996829  0.17701873]]


In [ ]:
#diagonal of a matrix
gfg = np.matrix('[6, 2; 3, 4]')
         
# applying matrix.diagonal() method
diag = gfg.diagonal()
   
print(diag)

[[6 4]]


In [ ]:
#matrix transpose
gfg = np.matrix('[4, 1; 12, 3]')
trans = gfg.transpose()
    
print(trans)

[[ 4 12]
 [ 1  3]]


In [ ]:
#trace of a matrix
gfg = np.matrix('[4, 1; 12, 3]')
tracem = gfg.trace()
    
print(tracem)

[[7]]
